#!/usr/local/bin/ruby

$LOAD_PATH.unshift('/home/mike/.localest/share/suspenders/ruby')

require '/home/mike/.localest/share/suspenders/gems/setup.rb'
require 'pathname'
require 'suspenders'

if ['create', '--create'].include? ARGV[0]
  ARGV.shift
  puts "[WARNING] the suspenders create argument is deprecated. Just use `suspenders #{ARGV.join}` instead"
end

templates_root = File.expand_path(File.join("..", "templates"), File.dirname(__FILE__))
Suspenders::AppGenerator.source_root templates_root
Suspenders::AppGenerator.source_paths << Rails::Generators::AppGenerator.source_root << templates_root

Suspenders::AppGenerator.start
